#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: MQTT Server & Web client
# Runs the MQTT Server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

if hass.config.false 'broker.enabled'; then
    while true; do
      hass.log.debug 'MQTT Server are not enabled...'
      exec sleep 86400
    done
fi

options+=(-c /opt/mosquitto.conf)

if hass.debug; then
  options+=(-v)
fi

hass.log.info "Starting mosquitto MQTT Server..."
exec mosquitto "${options[@]}"